spring:
  redis:
    timeout: 10s
    host: localhost
    port: 6379
    database: 1
    lettuce:
      pool:
        # 最大连接数
        max-active: 500
        # 最大空闲连接数
        max-idle: 100
        # 最大等待时间
        max-wait: 10s
        # 最小空闲连接数
        min-idle: 10
redis:
  key:
    defaultPrefix: fire-workorder